; PlatformIO Project Configuration File

;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:vanguard]
platform = ststm32
framework = arduino
board = VANGUARD
board_build.variants_dir = variants
board_build.variant = VANGUARD
build_flags =
	-D VANGUARD
	-I variants/VANGUARD
	-DPIO_FRAMEWORK_ARDUINO_ENABLE_CDC
	-DUSBD_USE_MSC
	-DUSBD_USE_CDC
	-DUSB_MSC_ENABLE
	-DUSBCON
	-DUSBD_VID=0
	-DUSBD_PID=0
	-Wa,-mfloat-abi=hard
	-Wa,-mfpu=fpv4-sp-d16
upload_protocol = dfu
lib_deps =
	adafruit/Adafruit LPS2X@^2.0.6
	sparkfun/SparkFun u-blox GNSS v3@^3.1.8
	adafruit/Adafruit LSM303DLHC @ ^1.0.4
	greiman/SdFat
	tomstewart89/BasicLinearAlgebra @ ^5.1
	Wire
	SPI
	Servo